- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObject.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
- src/main/java/net/ripe/rpki/commons/crypto/crl/X509Crl.java
- src/main/java/net/ripe/rpki/commons/crypto/crl/X509CrlBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateUtil.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/x509/pkcs10/RpkiCaCertificateRequestParser.java
- src/test/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectBuilderTest.java
Upgrade to Bouncy Castle 1.58. Most significant change is that CMS objects are generated with the "sha256WithRsa" signing algorithm identifier, as is required by the RPKI RFCs. CMS objects signed with "rsaEncyption" are still accepted when validating.
> Bouncycastle 1.58

- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/util/KeyStoreUtil.java
- src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectBuilder.java
- src/test/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectBuilderTest.java
Fix the provisioning CMS by not adding extra signed attributes to it.
> Exclude cmsAlgorithmProtect extension from ProvisioningCmsObjectBuilder.

- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParser.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParser.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java
- src/test/java/net/ripe/rpki/commons/provisioning/interop/CreateObjectsForInteropTesting.java
We have incorrect implementation of ROA and MFT parsing that always think the version is omitted, so parsers break whenever version is there. This is to fix the issue. Also signingTime attribute is optional.
> Fix ROA and MFT parsing

- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
- src/main/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidator.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationOptions.java
- src/main/java/net/ripe/rpki/commons/validation/objectvalidators/ResourceValidatorFactory.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidatorTest.java
- src/test/java/net/ripe/rpki/commons/provisioning/interop/ProcessIscUpdownPdusTest.java
Introduce strict check manifest and crl validity, to enable/disable max stale checking for crl and manifest.
Rename loose validation into allow overlaps, to make it distinct/clear.
> Setup options

- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/util/Asn1Util.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/AbstractX509CertificateWrapper.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateParser.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
Mainly reduce the amount of garbage generated for some commonly used functions. Speeds up the RPKI validator 3 by about 5%-10% when performing a full trust anchor validation.
> Performance improvements

- src/main/java/net/ripe/rpki/commons/validation/ValidationResult.java
- src/test/java/net/ripe/rpki/commons/validation/ValidationResultTest.java
Keeping track of all checks that passed uses a large amount of memory
in the RPKI validator, which does not use these passed checks at all.
By invoking `withoutStoringPassingChecks` on validation result it will no
longer store passed checks.
> Add option to ValidationResult to store only warnings and errors

- README.md
- src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectValidator.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationOptions.java
- src/main/java/net/ripe/rpki/commons/validation/objectvalidators/X509ResourceCertificateBottomUpValidator.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlTest.java
- src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidatorTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateTest.java
- src/test/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectValidatorTest.java
- src/test/java/net/ripe/rpki/commons/provisioning/interop/CreateObjectsForInteropTesting.java
- src/test/java/net/ripe/rpki/commons/provisioning/interop/ProcessIscUpdownPdusTest.java
- src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateParentChildValidatorTest.java
At the moment we have ValidationOptions.strictValidation() that was introduced for paranoidal testing of RIPE NCC's repository, but got into production validator and introduced weird errors when we start to complain about objects 7 hours before they expire. This PR introduce separate modes for normal strict validation (that we are transitioning to) and paranoid testing mode.
> Make ValidationOptions static constructors matching the reality

- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateParser.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateUtil.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/payload/common/CertificateElement.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationLocation.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationResult.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
- src/main/java/net/ripe/rpki/commons/validation/objectvalidators/X509ResourceCertificateBottomUpValidator.java
- src/main/resources/validation_en.properties
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParserTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParserTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateTest.java
- src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateBottomUpValidatorTest.java
Performs Subject Information Access (SIA) validations as specified by [RFC6487 section 4.8.8](https://tools.ietf.org/html/rfc6487#section-4.8.8).
Only generates a warning for EE certificates with a SIA rpkiNotify access methods since AFRINIC manifests contain this, even though it doesn't seem to be allowed by the RFC.
> Repository and manifest uri validation

- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
- src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParserTest.java
- src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateBottomUpValidatorTest.java
Matches RFC6487 section 4.4 and 4.5 now, except that we also accept UTF-8 strings.
Now we no longer warn about the "The issuer CN=e6c7f8d7-4c06-4480-bbd8-71cf97b216b6 does not have the correct format." from the APNIC TA.
> Stricter checking of certificate Subject and Issuer DN

- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateUtil.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
- src/main/resources/validation_en.properties
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
- src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateBottomUpValidatorTest.java
Only allow normal characters in manifest entry file names. RFC 6486 is
actually not clear what is allowed and simply requires that manifest
entries are published in the same repository as the manifest. Quote
from the RFC: "the name of the file in the repository publication
point (directory)".
We allow the characters from `DERPrintableString#isPrintableString`
except for slash (directory separator). We also allow the
underscore (`_`) since it is used by some certificate authorities
already.
Also ensure the rsync repository URI ends with a slash, so that manifest
entries resolve correctly using the `URI#resolve` method.
Finally, URIs should not be opaque (without path) and have at least the
hostname specified.
> Validate manifest entry file name

- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/util/Asn1Util.java
DEROutputStream was deprecated and replaced by ASN1OutputStream per
the recommendation [0].
[0]: https://github.com/bcgit/bc-java/blob/07604208a773d2334fb09276796288404804e557/core/src/main/java/org/bouncycastle/asn1/DEROutputStream.java#L15
> Upgrade to bouncy castle 1.67

- src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParser.java
- src/main/java/net/ripe/rpki/commons/crypto/util/Asn1Util.java
When investigating I found that ASN bounds are checked while the value is parsed. I've clarified this in the docstring so this is clearer to future readers/reviewers of the code.
@reviewer: please double check that my interpretation of the behaviour of the ASN constructors is correct.
> Clarify that bounds are checked during ASN parsing

- src/main/java/net/ripe/rpki/commons/ta/domain/request/ResourceCertificateRequestData.java
- src/main/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorRequestSerializer.java
Upstream CA requests include IP resources. While not used directly, they must be
stored in the object graph for lossless deserialization/serialization.
Because the TA signing requests don't contain IP resources and no expose the
`null` field too much, provide separate factory functions for these cases.
> ResourceCertificateRequest: optionally have an IPResourceSet

- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateBuilderTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509RouterCertificateBuilderTest.java
Drop two tests that try to prevent use of public key information with no obvious
reason not to.
> Check public key algorithm to be RSA

- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
Address unclarity on the use of open-ended certificates, as specified in RFC
5280. RPKI does not use open-ended certificates at this moment.
> Document `endDate` being non-nullable

- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelperTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509RouterCertificateBuilderTest.java
This make sure that ExtendedKeyUsage is not set except for router certificates (which nobody uses yet anyway).
> Add tests verifying that ExtendedKeyUsage is set/not set

- pom.xml
Update plugin `dependency-check-maven` to latest version. Plugin (both old and most recent versions) is broken due to parsing errors (see jeremylong/DependencyCheck#3310 for details), so disable the plugin temporarily until patched upstream.
> Dependency check maven

- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelperTest.java
RFC 5280 specifies that serial number MUST be a possitive integer and that
conforming CAs MUST NOT use serial numbers longer than 20 octets.
> Check issuer serial number boundaries

- src/main/java/net/ripe/rpki/commons/crypto/util/EncodedPublicKey.java
- src/test/java/net/ripe/rpki/commons/crypto/util/EncodedPublicKeyTest.java
Allow for `EncodedPublicKey` instances to be used as proper `PublicKey`
substitutes (fixing earlier substitution principle violations).
> EncodedPublicKey: properly implement PublicKey

- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
Document why matchesFiles does what it does so a future reviewer can be sure that it matches this description when reading it once (instead of reconstructing why this algorithm is enough).
Note that while this approach is fine for generating objects (where we want uniqueness) this this may be unable to properly represent some manifests that contain multiple files with the same name.
> Document matchesFiles for future reviewers

- src/main/java/net/ripe/rpki/commons/ta/domain/request/TrustAnchorRequest.java
Wicket wants it to be serialisable. Maybe JDK8, I didn't spend time investigating it.
> Make TrustAnchorRequest serialisable

- pom.xml
1.21 was released last week, but the release process doesn't automatically bump
the version.
> Bump version to 1.22-SNAPSHOT

- src/main/java/net/ripe/rpki/commons/crypto/util/KeyPairUtil.java
Use newer/simpler APIs to perform base64 and hex encoding.
> Simplify hex and base64 encoding

- src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningCmsCertificateBuilder.java
- src/test/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningCmsCertificateBuilderTest.java
@erikrozendaal unfortunately this will break your branch, but I would like this before 2.0
* Change default validity period to `now-1m ... now+15m`
* Allow validity period to be set externally (allows changes w/o a
release of commons)
> Update RFC 6492 validity period handling

- README.md
- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/cms/RPKIContentInfo.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
- src/test/java/net/ripe/rpki/commons/crypto/util/Asn1UtilTest.java
After #101 (because I expected merge conflicts in the README).
Changes for bouncy castle 1.70  
* Remove deprecated (and unused in RIPE NCC rpki projects) constructor
in our DER ContentInfo copy
* Patch test that decodes illegal input that bouncy castle now rejects
* Finally use binarysigningtime attribute from bouncycatle that we added with a PR on bouncy castle.
> Bouncy castle 1.70

- README.md
- pom.xml
Updated dependencies after whitesource notice (for non-vulnerable updates).
> guava, joda-time, saxon-he updates

- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParserTest.java
- src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateParentChildValidatorTest.java
- src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
- src/test/java/net/ripe/rpki/commons/validation/properties/URIGenTest.java
This pull request increases coverage on property tests by ensuring a test exercises code that was not previously encountered.  By adding a URI generator and adding crl distribution points to the **validParentChildSubResources** property test, overall coverage is improved.
I am a part of a research group at the University of Illinois Chicago that works towards novel methods to detect bugs in software projects. This project is identified as being a good candidate for application of our research method to improve coverage using property tests. The above issue outlines the findings with a pull request of the enhanced property test to document the observed behavior.
> Property test improvements

- README.md
- src/main/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtension.java
- src/main/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtensionParser.java
- src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificate.java
- src/test/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtensionTest.java
Extracted from the `X509ResourceCertificate` class to allow use of resource extensions without needing a resource certificate.
> Add class to represent RFC3779 the resource extension

- src/main/java/net/ripe/rpki/commons/crypto/cms/GenericRpkiSignedObjectParser.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParser.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/GenericRpkiSignedObjectParserTest.java
Finished the generic signed object parser. This time not pushing to main (`stash, checkout, pull, pop, [forget to switch branch and rebase], commit, push`). One additional benefit is that we can use this for conformance testing Signed Object specific checks w/o also relying on object parsing.
This could be moved in RpkiSignedObjectParser if that is made non-abstract.
> Finish generic signed object parser

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- README.md
- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/cms/GenericRpkiSignedObjectParser.java
- src/main/java/net/ripe/rpki/commons/crypto/util/SignedObjectUtil.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/GenericRpkiSignedObjectParserTest.java
- src/test/java/net/ripe/rpki/commons/util/SignedObjectUtilTest.java
> Access certificate with generic signed object parser

- README.md
- src/main/java/net/ripe/rpki/commons/util/RepositoryObjectType.java
> Add String representations for object types.

- README.md
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/crl/X509CrlBuilder.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCMSBuilderPropertyTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsBuilderTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParserTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
- src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlBuilderTest.java
This is to avoid mistakes with setting validity dates and getting them backwards (learned the hard way)
> Add withValidityPeriod to MFT and CRL builders

- README.md
- src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsBuilder.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaPrefix.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsBuilderTest.java
- src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaPrefixTest.java
Do not encode the max length in a ROA when it is present but redundant.
> Do not encode max length in ROA when it is redundant

- src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaPrefixTest.java
@lolepezy I think this is what you wanted. I agree that this is probably more exhaustive if it tests all pairs.
> Use EqualsTester for equals/hashcode relationships

- README.md
- pom.xml
- src/main/java/net/ripe/rpki/commons/crypto/IllegalAsn1StructureException.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParser.java
- src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParser.java
- src/main/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtensionParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/payload/PayloadParser.java
- src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningIdentityCertificateBuilder.java
- src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
- src/main/resources/validation_en.properties
- src/test/java/net/ripe/rpki/commons/crypto/cms/ghostbuster/GhostbustersCmsParserTest.java
- src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateUtilTest.java
- src/test/java/net/ripe/rpki/commons/interop/BBNRoaConformanceTest.java
- src/test/java/net/ripe/rpki/commons/provisioning/payload/list/response/ResourceClassListResponsePayloadSerializerTest.java
- src/test/java/net/ripe/rpki/commons/validation/interop/BBNConformanceTest.java
> Use bouncy castle 1.77

- README.md
- src/main/java/net/ripe/rpki/commons/provisioning/x509/pkcs10/RpkiCaCertificateRequestParser.java
- src/test/java/net/ripe/rpki/commons/provisioning/x509/pkcs10/RpkiCaCertificateRequestParserTest.java
> Wrap NPE when RpkiCaCertificateRequestParser fails

- ci_settings.xml
- pom.xml
oss.sonatype.org has been replaced by central.sonatype.org. Update the publication plugin and credentials.
> Release to central.sonatype.org

- pom.xml
> central-publishing-maven-plugin: fix server-id link to settings
