RIPE-NCC/rpki-commons

src/main/java/net/ripe/rpki/commons/crypto/cms/CMSUtils.java
src/main/java/net/ripe/rpki/commons/crypto/cms/RPKIContentInfo.java
src/main/java/net/ripe/rpki/commons/crypto/cms/RPKISignedData.java
src/main/java/net/ripe/rpki/commons/crypto/cms/RPKISignedDataGenerator.java
src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectBuilder.java
src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectBuilder.java
src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectParser.java
src/test/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectBuilderTest.java

- RPKIContentInfo, is based on bouncy castle [ContentInfo](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/cms/ContentInfo.java) encoding DERSequence instead of BERSequence
- RPKISignedData, is based on bouncy castle [SignedData](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/cms/SignedData.java) with toAsn1Primitive producing DER instead of BER
- RPKISignedDataGenerator, is based on bouncy castle [CMSSignedDataGenerator](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/cms/CMSSignedDataGenerator.java)
1be3e79

RPKISignedDataGenerator producing DER conforming RFC6488

---

src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
src/main/java/net/ripe/rpki/commons/crypto/util/KeyStoreUtil.java
src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectParser.java

This is to fix strange validation errors fir provisioning CMSs. BouncyCastle tries to verify signingTime fields that are optional according to https://tools.ietf.org/html/rfc6492

Fix provisioning cms

---

README.md
pom.xml

Revert bouncycastle version

---

README.md
pom.xml
src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
src/main/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidator.java
src/main/java/net/ripe/rpki/commons/validation/ValidationOptions.java
src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
src/main/resources/validation_en.properties
src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidatorTest.java
src/test/java/net/ripe/rpki/commons/provisioning/interop/ProcessIscUpdownPdusTest.java

A WIP for configurable validity period handling and rejection of objects from the future.

Pending discussion: configurable validity period handling

---

pom.xml
src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParser.java
src/main/java/net/ripe/rpki/commons/crypto/crl/X509Crl.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateParser.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificate.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateParser.java
src/main/java/net/ripe/rpki/commons/provisioning/payload/ProvisioningPayloadXmlSerializer.java
src/main/java/net/ripe/rpki/commons/validation/ValidationResult.java
src/main/java/net/ripe/rpki/commons/validation/objectvalidators/CertificateRepositoryObjectValidationContext.java
src/test/java/net/ripe/rpki/commons/crypto/util/KeyStoreUtilTest.java
src/test/java/net/ripe/rpki/commons/crypto/util/PregeneratedKeyPairFactory.java

Combined these changes add about 10% performance to trust anchor validation in the RPKI validator 3.
The changes mostly reflect reducing the number of allocations or unnecessary copies.

Performance improvements

---

src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
src/main/resources/validation_en.properties
src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java

See RFC 6486 section 4.4 item 3.

Validate manifest this update before next update

---

.github/workflows/ci.yml
pom.xml

* Bump xstream due to a security update.
* Incorporate other new dependencies
* Add github CI

Bump xstream due to security update + other dependencies

---

src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
src/test/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsTest.java
src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectPrinterTest.java

Use latest definition from sidrops mailing list.

Update manifest file name checks from RFC 6486bis

---

src/main/java/net/ripe/rpki/commons/xml/DomXmlSerializer.java

Move some DOM-related common code to commons.

Move some common methods into DomXmlSerialiser

---

src/main/java/net/ripe/rpki/commons/crypto/crl/X509CrlBuilder.java
src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlBuilderTest.java

Allow only CRL number that fit into 20 octets.

Crl number 20 octets max

---

src/main/java/net/ripe/rpki/commons/crypto/x509cert/GenericRpkiCertificateBuilder.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateBuilder.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509RouterCertificateBuilder.java
src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningCmsCertificateBuilder.java
src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsTest.java
src/test/java/net/ripe/rpki/commons/crypto/crl/X509CrlValidatorTest.java
src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificateBuilderTest.java
src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateBottomUpValidatorTest.java
src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateParentChildValidatorTest.java

This is to make sure SKI is always present.

Remove flag for optional SKI -- it's always true.

---

src/test/java/net/ripe/rpki/commons/crypto/cms/RPKISignedDataGeneratorTest.java

Add test highlighting and documenting the main difference of RPKISignedDataGenerator and original CMSSignedDataGenerator

Add more test on RPKI signed data

---

src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelper.java
src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelperTest.java

Make sure that the resource set complies to RFC requirement "at least
one of IP/AS extension must be present and marked critical".

Verify resource set.

---

src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java

See RFC 6488 section 2.1.1 and 2.1.6.1.

Check CMS object version and signer version

---

src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
src/main/resources/validation_en.properties
src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java

See https://tools.ietf.org/html/rfc6488#section-2.1.6.7 and https://tools.ietf.org/html/rfc6488#section-2.1.5

Validate CMS CRL and unsigned attributes are absent

---

README.md
src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentitySerializer.java
src/main/java/net/ripe/rpki/commons/provisioning/payload/AbstractProvisioningPayloadXmlSerializer.java
src/main/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorRequestSerializer.java
src/main/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorResponseSerializer.java
src/main/java/net/ripe/rpki/commons/util/XML.java
src/test/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorRequestSerializerTest.java
src/test/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorResponseSerializerTest.java
src/test/java/net/ripe/rpki/commons/util/XMLTest.java

* Add factory for non-namespace aware DocumentBuilder
* Explicitly name the factory methods depending on type.

Add factory for non-namespace aware DocumentBuilder

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.gitlab-ci.yml
pom.xml
src/main/java/net/ripe/rpki/commons/crypto/rfc3779/AddressFamily.java

Preparations on the CI side before renaming master to main.
Also adds CodeQL (~sonarcube but by github).

Rename master to main

---

README.md
pom.xml

Use ipresource 1.48

---

README.md
pom.xml

Depend on ipresource-1.49

---

README.md
pom.xml
src/test/java/net/ripe/rpki/commons/xml/XStreamXmlSerializerBuilderTest.java

* xstream 1.4.19
* add assertj, change two tests.

xstream 1.4.19

---

.gitignore
pom.xml
src/main/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequest.java
src/main/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequestSerializer.java
src/main/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponse.java
src/main/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponseSerializer.java
src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningCertificate.java
src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningIdentityCertificate.java
src/main/java/net/ripe/rpki/commons/xml/DomXmlSerializer.java
src/test/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequestSerializerTest.java
src/test/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponseSerializerTest.java

Implementation of RFC8183 `publisher_request` and `repository_response` classes and XML mapping.

RFC8183 publisher request repository response

---

src/main/java/net/ripe/rpki/commons/crypto/crl/X509Crl.java
src/main/java/net/ripe/rpki/commons/crypto/rfc3779/AddressFamily.java
src/main/java/net/ripe/rpki/commons/util/CsvFormatter.java
src/test/java/net/ripe/rpki/commons/ta/serializers/TrustAnchorResponseSerializerTest.java

Fix a number of CodeQL nits

---

README.md
pom.xml
src/main/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectPrinter.java
src/main/java/net/ripe/rpki/commons/crypto/x509cert/X509ResourceCertificate.java

X509 certificate immutable resource set

---

README.md
pom.xml
src/test/java/net/ripe/rpki/commons/crypto/util/Asn1UtilTest.java

Update dependencies and move to bouncy castle for JDK 1.8+

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.gitlab-ci.yml
README.md
pom.xml
src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsBuilder.java
src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaPrefix.java
src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsBuilderTest.java
src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParserTest.java
src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsTest.java
src/test/java/net/ripe/rpki/commons/crypto/cms/roa/RoaPrefixTest.java
src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectPrinterTest.java

Encode sorted, unique prefixes in ROAs

---

README.md
src/main/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtensionParser.java

Verify a number of MUSTS in resource extensions

---

README.md

Prepare for v1.35 release

---

README.md
pom.xml

Bouncy Castle 1.74

---

README.md
src/main/java/net/ripe/rpki/commons/crypto/util/SignedObjectUtil.java
src/test/java/net/ripe/rpki/commons/util/SignedObjectUtilTest.java

Also parse time from router certs

---

pom.xml

Prepare v1.37-SNAPSHOT

---

README.md
pom.xml

Use more modern version of jing

---

README.md
pom.xml
src/main/java/net/ripe/rpki/commons/crypto/IllegalAsn1StructureException.java
src/main/java/net/ripe/rpki/commons/crypto/cms/RpkiSignedObjectParser.java
src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCms.java
src/main/java/net/ripe/rpki/commons/crypto/cms/manifest/ManifestCmsParser.java
src/main/java/net/ripe/rpki/commons/crypto/cms/roa/RoaCmsParser.java
src/main/java/net/ripe/rpki/commons/crypto/rfc3779/ResourceExtensionParser.java
src/main/java/net/ripe/rpki/commons/provisioning/cms/ProvisioningCmsObjectParser.java
src/main/java/net/ripe/rpki/commons/provisioning/payload/PayloadParser.java
src/main/java/net/ripe/rpki/commons/provisioning/x509/ProvisioningIdentityCertificateBuilder.java
src/main/java/net/ripe/rpki/commons/validation/ValidationString.java
src/main/resources/validation_en.properties
src/test/java/net/ripe/rpki/commons/crypto/cms/ghostbuster/GhostbustersCmsParserTest.java
src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateUtilTest.java
src/test/java/net/ripe/rpki/commons/interop/BBNCMSConformanceTest.java
src/test/java/net/ripe/rpki/commons/interop/BBNCertificateConformanceTest.java
src/test/java/net/ripe/rpki/commons/interop/BBNRoaConformanceTest.java
src/test/java/net/ripe/rpki/commons/provisioning/payload/list/response/ResourceClassListResponsePayloadSerializerTest.java
src/test/java/net/ripe/rpki/commons/validation/interop/BBNConformanceTest.java

Improve resource extension parsing

---

README.md
pom.xml

release 1.37 and start 1.38

---

README.md
pom.xml

@bjpbakker I have hope that this fixes the build error encountered in the release build. Meanwhile, local release builds are fine.

newer dependency plugin

---

pom.xml

rpki commons 1.38

---

README.md
pom.xml

Remove the dependency-check-maven plugin

---

README.md
src/main/java/net/ripe/rpki/commons/validation/roa/AllowedRoute.java
src/main/java/net/ripe/rpki/commons/validation/roa/AnnouncedRoute.java
src/main/java/net/ripe/rpki/commons/validation/roa/RoaPrefixData.java
src/main/java/net/ripe/rpki/commons/validation/roa/RouteData.java
src/main/java/net/ripe/rpki/commons/validation/roa/RouteOriginValidationPolicy.java
src/test/java/net/ripe/rpki/commons/crypto/x509cert/X509CertificateBuilderHelperTest.java
src/test/java/net/ripe/rpki/commons/validation/AllowedRouteTest.java
src/test/java/net/ripe/rpki/commons/validation/roa/RouteOriginValidationPolicyTest.java

Validation state logic should use interface types

---

README.md
pom.xml

Remove Saxon-HE
